const pageContent = {
    ID: {
      searchnav: "cari menu berdasar nama...",
      MonthList: ["Jan","Feb","Mar","Apr",
                  "Mei","Jun","Jul","Agu",
                  "Sep", "Okt","Nov","Des"],
      loadingMessage: "Mohon Tunggu Permintaan Anda Sedang Diproses",
      emptyOR: "Mohon pilih Nomor Pesanan terlebih dahulu !",
      emptyprocod: "Mohon pilih Produk terlebih dahulu !",
      datanotfound: "tidak ditemukan !\n" +
                    "Pastikan Nomor Pesanan yang anda masukan sudah benar !",
      dataconfirm: "sudah di konfirmasi !",
      datanotconfirm: "belum di konfirmasi !",
      confirmsuccess: "berhasil di konfimasi !",
      confirmnotsuccess: "gagal di konfimasi !",
      deleteconfirm: "Yakin akan menghapus item ini ?",
      deletesuccess: "berhasil di hapus !",
      deletenotsuccess: "gagal di hapus !",
      add: "Tambah",
      edit: "Ubah",
      del: "Hapus",
      save: "Simpan",
      cancel: "Batal",
      print: "Cetak",
      RO:{
          printRO:{
            SPO:"SURAT PESANAN OUTLET",
            noSPO:"No. Pesanan",
            pharmacyname: "Nama Apotek",
            outletcode: "Kode Outlet",   
            address: "Alamat",
            to: "Kepada",
            date:"Tanggal",
            orderBy: "Pemesan",    
            fieldprocod: "Produk",
            fieldname: "Nama Produk", 
            fieldqtyOR: "Qty Pesanan",
          },
          taball: "SEMUA",
          tablocal: "LOKAL",
          tabelRO: {
            fieldprocod: "Produk",
            fieldname: "Nama Produk",
            fieldstock: "Stok",
            fieldtglconfirm: "Tgl Konfirmasi",
            fieldunitOR: "Satuan Pesanan",
            fieldqtyRec: "Qty Rekomen",
            fieldqtyOR: "Qty Pesanan",
            fieldlimitOR: "Batas Pesanan",
            fieldsisa: "Sisa",
            fieldprice: "Harga",
            fieldpricetot: "Total Harga",
          },
          lblgtotal: "Grand Total",
          lbltotalqty: "Total Qty",
          outlet: "Outlet",
          noorder: "No Pesanan",
          status: "Status Pesanan",
          tglconfirm: "Tgl Konfirmasi",
          confirm: "Dikonfirmasi",
          product: "Produk",
          qtyRec: "Qty Rekomen",
          qtyOR: "Qty Pesanan",
          qtySell: "Qty Jual",
          stock: "Stok",
          unitOR: "Satuan Pesanan",
          unitSell: "Satuan Jual",
          limitOR: "Batas Pesanan",
          sisa: "Sisa",
          lclprod: "Produk Lokal",
          price: "Harga",
          pricetot: "Total Harga",
          note: "Ket. OR",
          holdOR: "Pesanan Tertahan",
          stok: "Stok",
          minOR: "Min Pesanan",
          maxOR: "Max Pesanan",
          requestblank: "Permintaan Baru",
          request: "Permintaan Baru Auto",
          konfirmasi: "Konfirmasi",
          purchnumber: "No. Pembelian",
          purchdate: "Tgl. Pembelian",
          alocnumber: "No. Alokasi",
          alocdate: "Tgl. Alokasi",
          transnumber: "No. Transfer",
          transdate: "Tgl. Transfer",
          receivenumber: "No. Penerimaan",
          receivedate: "Tgl. Penerimaan",
          cancelcode: "Kode Pembatalan",
          canceldate: "Tgl. Pembatalan",
          usrupdate: "User Ubah",
          dateupdate: "Tgl. Ubah",
      }
    },
    EN: {
      searchnav: "search menu by name...",
      MonthList: ["Jan","Feb","Mar","Apr",
                  "May","Jun","Jul","Aug",
                  "Sep", "Oct","Nov","Dec"],
      loadingMessage: "Please Wait Your Request is Being Processed",
      emptyOR: "Please select Order Number first !",
      emptyprocod: "Please select Product first !",
      datanotfound: "not found !\n" +
                    "Make sure the inputed number is correct !",
      dataconfirm: "has been confirmed !",
      datanotconfirm: "UnConfirmed !",
      confirmsuccess: "confirm success !",
      confirmnotsuccess: "confirm failed !",
      deleteconfirm: "Are you sure you wish to delete this item ?",
      deletesuccess: "delete success !",
      deletenotsuccess: "delete failed !",
      add: "Add",
      edit: "Update",
      del: "Delete",
      save: "Save",
      cancel: "Cancel",
      print: "Print",
      RO:{
          printRO:{
            SPO:"OUTLET REPEAT ORDER",
            noSPO:"Order No.",
            pharmacyname: "Pharmacy Name",
            outletcode: "Outlet Code",
            address: "Address",
            to: "To",
            date:"Date",
            orderBy: "Order by",
            fieldprocod: "Procode",
            fieldname: "Product Name", 
            fieldqtyOR: "Order Qty",
          },
          taball: "ALL",
          tablocal: "LOCAL",
          tabelRO: {
            fieldprocod: "Procode",
            fieldname: "Product Name",
            fieldstock: "Stock",
            fieldtglconfirm: "Confirm Date",
            fieldunitOR: "Order Pack",
            fieldqtyRec: "Recommend Qty",
            fieldqtyOR: "Order Qty",
            fieldlimitOR: "Order Limit",
            fieldsisa: "Remain",
            fieldprice: "Net Price",
            fieldpricetot: "Net Price Total",
          },
          lblgtotal: "Grand Total",
          lbltotalqty: "Total Qty",
          outlet: "Outlet",
          noorder: "Order No",
          status: "Order Status",
          tglconfirm: "Confirm Date",
          confirm: "Comfirm By",
          product: "Procode",
          qtyRec: "Recommend Qty",
          qtyOR: "Order Qty",
          qtySell: "Sell Qty",
          stock: "Stock",
          unitOR: "Order Pack",
          unitSell: "Sell Pack",
          limitOR: "Order Limit",
          sisa: "Remain",
          lclprod: "Local Product",
          price: "Net Price",
          pricetot: "Net Price Total",
          note: "Note OR",
          holdOR: "Order Hold",
          stok: "Stock",
          minOR: "Min Order",
          maxOR: "Max Order",
          requestblank: "New Request",
          request: "New Request Auto",
          konfirmasi: "Confirm",
          purchnumber: "Purchase No.",
          purchdate: "Purchase Date",
          alocnumber: "Alokasi No.",
          alocdate: "Alokasi Date",
          transnumber: "Transfer No.",
          transdate: "Transfer Date",
          receivenumber: "Receive No.",
          receivedate: "Receive Date",
          cancelcode: "Cancel Code",
          canceldate: "Cancel Date",
          usrupdate: "User Update",
          dateupdate: "Update Date",
      },
    },
  };
  export default pageContent;
  